### ISSUE TITLE
 make lesson-md remakes all _episodes_rmd not just new ones

### ISSUE THREAD

**Issue by alanocallaghan** [carpentries-incubator/template#5]
I guess maybe this is intended behaviour in case files depend on each other, but I find it very annoying that my entire site needs remade every time one file changes by one line.

I'm patching this in my lesson, can bring it upstream if that sounds interesting. Otherwise just voicing my opinion

Solution here: https://github.com/carpentries-incubator/high-dimensional-stats-r/blob/gh-pages/Makefile

Since I was doing some faff to automatically build slides from the images, there's a bit more there than is strictly necessary.

**Comment by fmichonneau** [comment]
Thank you for bringing this up.

We agree that this can be annoying especially when working on a lesson with episodes that take a long time to render. We are glad that you have found a solution that works for you! One of the reasons we use open source tools for our infrastructure is so that users can modify it to suit their needs.

As you may know, we are working on a new version of the lesson infrastructure, which incorporates caching and lead to faster rendering times as only episodes that have changed will be compiled to HTML.

Generalizing your approach to other lessons will represent a sunk time cost both in terms of development and maintenance, so we can't commit to changing our build scripts at the time.
